version: "3"

services:
  lanpage:
    image: lanpage:latest
    build:
      context: .
      dockerfile: Dockerfile
    # Comment in the line below if running docker or rootful podman
    #network_mode: host
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
